name: CI
on:
  push:
    branches:
      - master
    tags:
      - "!*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Get dependencies
        run: |
          go mod download
      - name: Test
        run: |
          go test -v ./...
        env:
          TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
          TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
          TWITTER_MFA_SECRET: ${{ secrets.TWITTER_MFA_SECRET }}
